//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMEL_Carrer
{


    public partial class FirstPage
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFirstName;
        protected global::System.Web.UI.WebControls.TextBox txtLastName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLastName;
        protected global::System.Web.UI.WebControls.TextBox txtFatherName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFatherName;
        protected global::System.Web.UI.WebControls.TextBox txtDateOfBirth;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDateOfBirth;
        protected global::System.Web.UI.WebControls.DropDownList ddlGender;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvGender;
        protected global::System.Web.UI.WebControls.DropDownList ddlMaritalStatus;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;
        protected global::System.Web.UI.WebControls.TextBox txtPhone;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPhone;
        protected global::System.Web.UI.WebControls.TextBox txtAddress;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAddress;
        protected global::System.Web.UI.WebControls.TextBox txtCity;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCity;
        protected global::System.Web.UI.WebControls.TextBox txtState;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvState;
        protected global::System.Web.UI.WebControls.TextBox txtPinCode;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPinCode;
        protected global::System.Web.UI.WebControls.DropDownList ddlHighestQualification;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvQualification;
        protected global::System.Web.UI.WebControls.TextBox txtSpecialization;
        protected global::System.Web.UI.WebControls.TextBox txtUniversity;
        protected global::System.Web.UI.WebControls.TextBox txtYearOfPassing;
        protected global::System.Web.UI.WebControls.TextBox txtPercentage;
        protected global::System.Web.UI.WebControls.TextBox txtTotalExperience;
        protected global::System.Web.UI.WebControls.TextBox txtCurrentCompany;
        protected global::System.Web.UI.WebControls.TextBox txtCurrentDesignation;
        protected global::System.Web.UI.WebControls.TextBox txtCurrentSalary;
        protected global::System.Web.UI.WebControls.DropDownList ddlPositionApplied;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPosition;
        protected global::System.Web.UI.WebControls.TextBox txtExpectedSalary;
        protected global::System.Web.UI.WebControls.FileUpload fuPassportPhoto;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPhoto;
        protected global::System.Web.UI.WebControls.FileUpload fuResume;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvResume;
        protected global::System.Web.UI.WebControls.TextBox txtAdditionalInfo;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
        protected global::System.Web.UI.WebControls.Button btnCancel;

        /// <summary>
        /// btnSaveDraft control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSaveDraft;
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
